//auth

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_REQUEST = "REGISTER_REQUEST";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const UPDATE_ME_REQUEST = "UPDATE_ME_REQUEST";
export const UPDATE_ME_SUCCESS = "UPDATE_ME_SUCCESS";
export const UPDATE_ME_FAIL = "UPDATE_ME_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const DELETE_ME_REQUEST = "DELETE_ME_REQUEST";
export const DELETE_ME_SUCCESS = "DELETE_ME_SUCCESS";
export const DELETE_ME_FAIL = "DELETE_ME_FAIL";

export const GOOGLE_AUTH_SIGNIN_REQUEST = "GOOGLE_AUTH_SIGNIN_SIGNIN_REQUEST";
export const GOOGLE_AUTH_SIGNIN_SUCCESS = "GOOGLE_AUTH_SIGNIN_SUCCESS";
export const GOOGLE_AUTH_SIGNIN_FAIL = "GOOGLE_AUTH_SIGNIN_FAIL";

export const FACEBOOK_AUTH_SIGNIN_REQUEST =
  "FACEBOOK_AUTH_SIGNIN_SIGNIN_REQUEST";
export const FACEBOOK_AUTH_SIGNIN_SUCCESS = "FACEBOOK_AUTH_SIGNIN_SUCCESS";
export const FACEBOOK_AUTH_SIGNIN_FAIL = "FACEBOOK_AUTH_SIGNIN_FAIL";

export const UPDATE_MY_PASSWORD_REQUEST = "UPDATE_MY_PASSWORD_SIGNIN_REQUEST";
export const UPDATE_MY_PASSWORD_SUCCESS = "UPDATE_MY_PASSWORD_SUCCESS";
export const UPDATE_MY_PASSWORD_FAIL = "UPDATE_MY_PASSWORD_FAIL";
