export const CREATE_CATERGORY_REQUEST = "CREATE_CATERGORY_REQUEST";
export const CREATE_CATERGORY_SUCCESS = "CREATE_CATERGORY_SUCCESS";
export const CREATE_CATERGORY_FAIL = "CREATE_CATERGORY_FAIL";

export const UPDATE_CATERGORY_REQUEST = "UPDATE_CATERGORY_REQUEST";
export const UPDATE_CATERGORY_SUCCESS = "UPDATE_CATERGORY_SUCCESS";
export const UPDATE_CATERGORY_FAIL = "UPDATE_CATERGORY_FAIL";

export const DELETE_CATERGORY_REQUEST = "DELETE_CATERGORY_REQUEST";
export const DELETE_CATERGORY_SUCCESS = "DELETE_CATERGORY_SUCCESS";
export const DELETE_CATERGORY_FAIL = "DELETE_CATERGORY_FAIL";

export const GET_CATERGORY_REQUEST = "GET_CATERGORY_REQUEST";
export const GET_CATERGORY_SUCCESS = "GET_CATERGORY_SUCCESS";
export const GET_CATERGORY_FAIL = "GET_CATERGORY_FAIL";

export const GET_CATERGORIES_REQUEST = "GET_CATERGORIES_REQUEST";
export const GET_CATERGORIES_SUCCESS = "GET_CATERGORIES_SUCCESS";
export const GET_CATERGORIES_FAIL = "GET_CATERGORIES_FAIL";
