export const CREATE_EMAIL_CAMPAIGN_REQUEST = "CREATE_EMAIL_CAMPAIGN_REQUEST";
export const CREATE_EMAIL_CAMPAIGN_SUCCESS = "CREATE_EMAIL_CAMPAIGN_SUCCESS";
export const CREATE_EMAIL_CAMPAIGN_FAIL = "CREATE_EMAIL_CAMPAIGN_FAIL";

export const GET_EMAIL_CAMPAIGNS_REQUEST = "GET_EMAIL_CAMPAIGNS_REQUEST";
export const GET_EMAIL_CAMPAIGNS_SUCCESS = "GET_EMAIL_CAMPAIGNS_SUCCESS";
export const GET_EMAIL_CAMPAIGNS_FAIL = "GET_EMAIL_CAMPAIGNS_FAIL";
