//newletter
export const JOIN_MAILING_LIST_REQUEST = "JOIN_MAILING_LIST_REQUEST";
export const JOIN_MAILING_LIST_SUCCESS = "JOIN_MAILING_LIST_SUCCESS";
export const JOIN_MAILING_LIST_FAIL = "JOIN_MAILING_LIST_FAIL";

export const UPDATE_MAILING_LIST_REQUEST = "UPDATE_MAILING_LIST_REQUEST";
export const UPDATE_MAILING_LIST_SUCCESS = "UPDATE_MAILING_LIST_SUCCESS";
export const UPDATE_MAILING_LIST_FAIL = "UPDATE_MAILING_LIST_FAIL";

export const GET_MAILING_LIST_REQUEST = "GET_MAILING_LIST_REQUEST";
export const GET_MAILING_LIST_SUCCESS = "GET_MAILING_LIST_SUCCESS";
export const GET_MAILING_LIST_FAIL = "GET_MAILING_LIST_FAIL";
