export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL";

export const GET_UNBALANCED_SALES_REQUEST = "GET_UNBALANCED_SALES_REQUEST";
export const GET_UNBALANCED_SALES_SUCCESS = "GET_UNBALANCED_SALES_SUCCESS";
export const GET_UNBALANCED_SALES_FAIL = "GET_UNBALANCED_SALES_FAIL";

export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAIL = "CHECKOUT_FAIL";

export const GET_ORDERS_LIST_REQUEST = "GET_ORDERS_LIST_REQUEST";
export const GET_ORDERS_LIST_SUCCESS = "GET_ORDERS_LIST_SUCCESS";
export const GET_ORDERS_LIST_FAIL = "GET_ORDERS_LIST_FAIL";

export const GET_PLUG_SALES_LIST_REQUEST = "GET_PLUG_SALES_LIST_REQUEST";
export const GET_PLUG_SALES_LIST_SUCCESS = "GET_PLUG_SALES_LIST_SUCCESS";
export const GET_PLUG_SALES_LIST_FAIL = "GET_PLUG_SALES_LIST_FAIL";

export const GET_PLUG_WEEKLY_STATS_REQUEST = "GET_PLUG_WEEKLY_STATS_REQUEST";
export const GET_PLUG_WEEKLY_STATS_SUCCESS = "GET_PLUG_WEEKLY_STATS_SUCCESS";
export const GET_PLUG_WEEKLY_STATS_FAIL = "GET_PLUG_WEEKLY_STATS_FAIL";

export const GET_PLUG_DAILY_STATS_REQUEST = "GET_PLUG_DAILY_STATS_REQUEST";
export const GET_PLUG_DAILY_STATS_SUCCESS = "GET_PLUG_DAILY_STATS_SUCCESS";
export const GET_PLUG_DAILY_STATS_FAIL = "GET_PLUG_DAILY_STATS_FAIL";
