export const CREATE_PLUG_REVIEW_REQUEST = "CREATE_PLUG_REVIEW_REQUEST";
export const CREATE_PLUG_REVIEW_SUCCESS = "CREATE_PLUG_REVIEW_SUCCESS";
export const CREATE_PLUG_REVIEW_FAIL = "CREATE_PLUG_REVIEW_FAIL";

export const UPDATE_PLUG_REVIEW_REQUEST = "UPDATE_PLUG_REVIEW_REQUEST";
export const UPDATE_PLUG_REVIEW_SUCCESS = "UPDATE_PLUG_REVIEW_SUCCESS";
export const UPDATE_PLUG_REVIEW_FAIL = "UPDATE_PLUG_REVIEW_FAIL";

export const DELETE_PLUG_REVIEW_REQUEST = "DELETE_PLUG_REVIEW_REQUEST";
export const DELETE_PLUG_REVIEW_SUCCESS = "DELETE_PLUG_REVIEW_SUCCESS";
export const DELETE_PLUG_REVIEW_FAIL = "DELETE_PLUG_REVIEW_FAIL";

export const GET_PLUG_REVIEW_REQUEST = "GET_PLUG_REVIEW_REQUEST";
export const GET_PLUG_REVIEW_SUCCESS = "GET_PLUG_REVIEW_SUCCESS";
export const GET_PLUG_REVIEW_FAIL = "GET_PLUG_REVIEW_FAIL";

export const GET_PLUG_REVIEWS_REQUEST = "GET_PLUG_REVIEWS_REQUEST";
export const GET_PLUG_REVIEWS_SUCCESS = "GET_PLUG_REVIEWS_SUCCESS";
export const GET_PLUG_REVIEWS_FAIL = "GET_PLUG_REVIEWS_FAIL";
