//plugs
export const CREATE_PLUG_REQUEST = "CREATE_PLUG_REQUEST";
export const CREATE_PLUG_SUCCESS = "CREATE_PLUG_SUCCESS";
export const CREATE_PLUG_FAIL = "CREATE_PLUG_FAIL";

export const UPDATE_PLUG_REQUEST = "UPDATE_PLUG_REQUEST";
export const UPDATE_PLUG_SUCCESS = "UPDATE_PLUG_SUCCESS";
export const UPDATE_PLUG_FAIL = "UPDATE_PLUG_FAIL";

export const DELETE_PLUG_REQUEST = "DELETE_PLUG_REQUEST";
export const DELETE_PLUG_SUCCESS = "DELETE_PLUG_SUCCESS";
export const DELETE_PLUG_FAIL = "DELETE_PLUG_FAIL";

export const GET_PLUG_REQUEST = "GET_PLUG_REQUEST";
export const GET_PLUG_SUCCESS = "GET_PLUG_SUCCESS";
export const GET_PLUG_FAIL = "GET_PLUG_FAIL";

export const GET_MY_PLUG_REQUEST = "GET_MY_PLUG_REQUEST";
export const GET_MY_PLUG_SUCCESS = "GET_MY_PLUG_SUCCESS";
export const GET_MY_PLUG_FAIL = "GET_MY_PLUG_FAIL";

export const GET_PLUGS_REQUEST = "GET_PLUGS_REQUEST";
export const GET_PLUGS_SUCCESS = "GET_PLUGS_SUCCESS";
export const GET_PLUGS_FAIL = "GET_PLUGS_FAIL";

export const GET_PLUGS_BY_CATERGORY_REQUEST = "GET_PLUGS_BY_CATERGORY_REQUEST";
export const GET_PLUGS_BY_CATERGORY_SUCCESS = "GET_PLUGS_BY_CATERGORY_SUCCESS";
export const GET_PLUGS_BY_CATERGORY_FAIL = "GET_PLUGS_BY_CATERGORY_FAIL";

export const FOLLOW_PLUG_REQUEST = "FOLLOW_PLUG_REQUEST";
export const FOLLOW_PLUG_SUCCESS = "FOLLOW_PLUG_SUCCESS";
export const FOLLOW_PLUG_FAIL = "FOLLOW_PLUG_FAIL";

export const UNFOLLOW_PLUG_REQUEST = "UNFOLLOW_PLUG_REQUEST";
export const UNFOLLOW_PLUG_SUCCESS = "UNFOLLOW_PLUG_SUCCESS";
export const UNFOLLOW_PLUG_FAIL = "UNFOLLOW_PLUG_FAIL";
