// products
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS_FOR_USER_FEED_REQUEST =
  "GET_PRODUCTS_FOR_USER_FEED_REQUEST";
export const GET_PRODUCTS_FOR_USER_FEED_SUCCESS =
  "GET_PRODUCTS_FOR_USER_FEED_SUCCESS";
export const GET_PRODUCTS_FOR_USER_FEED_FAIL =
  "GET_PRODUCTS_FOR_USER_FEED_FAIL";

export const GET_SEARCHED_PRODUCTS_REQUEST = "GET_SEARCHED_PRODUCTS_REQUEST";
export const GET_SEARCHED_PRODUCTS_SUCCESS = "GET_SEARCHED_PRODUCTS_SUCCESS";
export const GET_SEARCHED_PRODUCTS_FAIL = "GET_SEARCHED_PRODUCTS_FAIL";

export const GET_RANDOM_PRODUCTS_BY_PLUG_REQUEST =
  "GET_RANDOM_PRODUCTS_BY_PLUG_REQUEST";
export const GET_RANDOM_PRODUCTS_BY_PLUG_SUCCESS =
  "GET_RANDOM_PRODUCTS_BY_PLUG_SUCCESS";
export const GET_RANDOM_PRODUCTS_BY_PLUG_FAIL =
  "GET_RANDOM_PRODUCTS_BY_PLUG_FAIL";

export const GET_PRODUCTS_BY_PLUG_REQUEST = "GET_PRODUCTS_BY_PLUG_REQUEST";
export const GET_PRODUCTS_BY_PLUG_SUCCESS = "GET_PRODUCTS_BY_PLUG_SUCCESS";
export const GET_PRODUCTS_BY_PLUG_FAIL = "GET_PRODUCTS_BY_PLUG_FAIL";

export const GET_PRODUCTS_BY_PLUG_FRONTPAGE_REQUEST =
  "GET_PRODUCTS_BY_PLUG_FRONTPAGE_REQUEST";
export const GET_PRODUCTS_BY_PLUG_FRONTPAGE_SUCCESS =
  "GET_PRODUCTS_BY_PLUG_FRONTPAGE_SUCCESS";
export const GET_PRODUCTS_BY_PLUG_FRONTPAGE_FAIL =
  "GET_PRODUCTS_BY_PLUG_FRONTPAGE_FAIL";

export const GET_POPULAR_PRODUCTS_REQUEST = "GET_POPULAR_PRODUCTS_REQUEST";
export const GET_POPULAR_PRODUCTS_SUCCESS = "GET_POPULAR_PRODUCTS_SUCCESS";
export const GET_POPULAR_PRODUCTS_FAIL = "GET_POPULAR_PRODUCTS_FAIL";

export const GET_NEW_ARRIVALS_PRODUCTS_REQUEST =
  "GET_NEW_ARRIVALS_PRODUCTS_REQUEST";
export const GET_NEW_ARRIVALS_PRODUCTS_SUCCESS =
  "GET_NEW_ARRIVALS_PRODUCTS_SUCCESS";
export const GET_NEW_ARRIVALS_PRODUCTS_FAIL = "GET_NEW_ARRIVALS_PRODUCTS_FAIL";

export const GET_FILTERED_PRODUCTS_REQUEST = "GET_FILTERED_PRODUCTS_REQUEST";
export const GET_FILTERED_PRODUCTS_SUCCESS = "GET_FILTERED_PRODUCTS_SUCCESS";
export const GET_FILTERED_PRODUCTS_FAIL = "GET_FILTERED_PRODUCTS_FAIL";

export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_FAIL = "PRODUCTS_FAIL";
export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";

export const GET_PRODUCTS_STATS_SUCCESS = "GET_PRODUCTS_STATS_SUCCESS";
export const GET_PRODUCTS_STATS_FAIL = "GET_PRODUCTS_STATS_FAIL";
export const GET_PRODUCTS_STATS_REQUEST = "GET_PRODUCTS_STATS_REQUEST";

export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAIL = "ADD_TO_WISHLIST_FAIL";
export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
