export const CREATE_PRODUCT_REVIEW_REQUEST = "CREATE_PRODUCT_REVIEW_REQUEST";
export const CREATE_PRODUCT_REVIEW_SUCCESS = "CREATE_PRODUCT_REVIEW_SUCCESS";
export const CREATE_PRODUCT_REVIEW_FAIL = "CREATE_PRODUCT_REVIEW_FAIL";

export const UPDATE_PRODUCT_REVIEW_REQUEST = "UPDATE_PRODUCT_REVIEW_REQUEST";
export const UPDATE_PRODUCT_REVIEW_SUCCESS = "UPDATE_PRODUCT_REVIEW_SUCCESS";
export const UPDATE_PRODUCT_REVIEW_FAIL = "UPDATE_PRODUCT_REVIEW_FAIL";

export const DELETE_PRODUCT_REVIEW_REQUEST = "DELETE_PRODUCT_REVIEW_REQUEST";
export const DELETE_PRODUCT_REVIEW_SUCCESS = "DELETE_PRODUCT_REVIEW_SUCCESS";
export const DELETE_PRODUCT_REVIEW_FAIL = "DELETE_PRODUCT_REVIEW_FAIL";

export const GET_PRODUCT_REVIEW_REQUEST = "GET_PRODUCT_REVIEW_REQUEST";
export const GET_PRODUCT_REVIEW_SUCCESS = "GET_PRODUCT_REVIEW_SUCCESS";
export const GET_PRODUCT_REVIEW_FAIL = "GET_PRODUCT_REVIEW_FAIL";

export const GET_PRODUCT_REVIEWS_REQUEST = "GET_PRODUCT_REVIEWS_REQUEST";
export const GET_PRODUCT_REVIEWS_SUCCESS = "GET_PRODUCT_REVIEWS_SUCCESS";
export const GET_PRODUCT_REVIEWS_FAIL = "GET_PRODUCT_REVIEWS_FAIL";
