export const CREATE_REFUND_REQUEST = "CREATE_REFUND_REQUEST";
export const CREATE_REFUND_SUCCESS = "CREATE_REFUND_SUCCESS";
export const CREATE_REFUND_FAIL = "CREATE_REFUND_FAIL";

export const UPDATE_REFUND_REQUEST = "UPDATE_REFUND_REQUEST";
export const UPDATE_REFUND_SUCCESS = "UPDATE_REFUND_SUCCESS";
export const UPDATE_REFUND_FAIL = "UPDATE_REFUND_FAIL";

export const GET_REFUND_REQUEST = "GET_REFUND_REQUEST";
export const GET_REFUND_SUCCESS = "GET_REFUND_SUCCESS";
export const GET_REFUND_FAIL = "GET_REFUND_FAIL";

export const GET_REFUNDS_REQUEST = "GET_REFUNDS_REQUEST";
export const GET_REFUNDS_SUCCESS = "GET_REFUNDS_SUCCESS";
export const GET_REFUNDS_FAIL = "GET_REFUNDS_FAIL";
