export const CREATE_SUBCATERGORY_REQUEST = "CREATE_SUBCATERGORY_REQUEST";
export const CREATE_SUBCATERGORY_SUCCESS = "CREATE_SUBCATERGORY_SUCCESS";
export const CREATE_SUBCATERGORY_FAIL = "CREATE_SUBCATERGORY_FAIL";

export const UPDATE_SUBCATERGORY_REQUEST = "UPDATE_SUBCATERGORY_REQUEST";
export const UPDATE_SUBCATERGORY_SUCCESS = "UPDATE_SUBCATERGORY_SUCCESS";
export const UPDATE_SUBCATERGORY_FAIL = "UPDATE_SUBCATERGORY_FAIL";

export const DELETE_SUBCATERGORY_REQUEST = "DELETE_SUBCATERGORY_REQUEST";
export const DELETE_SUBCATERGORY_SUCCESS = "DELETE_SUBCATERGORY_SUCCESS";
export const DELETE_SUBCATERGORY_FAIL = "DELETE_SUBCATERGORY_FAIL";

export const GET_SUBCATERGORY_REQUEST = "GET_SUBCATERGORY_REQUEST";
export const GET_SUBCATERGORY_SUCCESS = "GET_SUBCATERGORY_SUCCESS";
export const GET_SUBCATERGORY_FAIL = "GET_SUBCATERGORY_FAIL";

export const GET_SUBCATERGORIES_REQUEST = "GET_SUBCATERGORIES_REQUEST";
export const GET_SUBCATERGORIES_SUCCESS = "GET_SUBCATERGORIES_SUCCESS";
export const GET_SUBCATERGORIES_FAIL = "GET_SUBCATERGORIES_FAIL";
